# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_pytanie_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odpowiedz',
            old_name='quesion',
            new_name='question',
        ),
    ]
