# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20160511_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('hint', models.CharField(max_length=128)),
                ('answer', models.TextField()),
                ('answer_type', models.CharField(choices=[(b'Plain text', b'Plain text'), (b'List', b'List'), (b'Steps', b'Steps'), (b'Table', b'Table')], max_length=12)),
            ],
        ),
        migrations.RenameModel(
            old_name='Kierunek',
            new_name='Quiz_Set',
        ),
        migrations.RemoveField(
            model_name='odpowiedz',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pytanie',
            name='spec',
        ),
        migrations.DeleteModel(
            name='Odpowiedz',
        ),
        migrations.DeleteModel(
            name='Pytanie',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Quiz_Set'),
        ),
    ]
